apiVersion: v1
kind: Secret
metadata:
  name: test-nginx-ca-secret
  namespace: cert-manager
type: Opaque
data:
  tls.crt:  # content of ca.crt (converted to base64)
  tls.key:  # content of ca.key (converted to base64)
